comment: false
ignore:
- setup.py
coverage:
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
        paths:
        - "names_matcher"
